[package]
name = "psd-manager"
version = "0.1.15"
description = "Psd Manager - 密码管理器"
authors = ["FanYanJun"]
edition = "2021"

[lib]
name = "psd_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "psd-manager"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
aes-gcm = "0.11"
fs4 = { version = "1.1.0", default-features = false, features = ["sync"] }
keyring = "4.1.4"
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2.4.2"
